In [1]:
import pandas as pd
import openpyxl as exc
from openpyxl import workbook as wb
import xlrd
import pyexcel as p
import os

In [2]:
import locale
from locale import atof
locale.setlocale(locale.LC_NUMERIC, '')

'English_United States.1252'

In [3]:
#pathhs
path97 = r'C:\Users\willd\OneDrive\Desktop\Belair\crew report\97_format'
path10 = r'C:\Users\willd\OneDrive\Desktop\Belair\crew report\10_format\\'

In [3]:
#for loop to convert 97 format to 10 
for item in os.listdir(path97):
    full_path = os.path.join(path97, item)
    name = item.split('.')[0]
    new_name = name + '.xlsx'
    p.save_book_as(file_name=(full_path),dest_file_name= path10 + new_name)

WARNING *** file size (72801) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** file size (55530) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** file size (76577) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** file size (46680) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** file size (91130) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** file size (58927) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** file size (43892) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** file size (91081) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** file size (61665) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** file size (60747) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** file size (61134) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** file size (90745) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** file size (52817) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero
WARNING *** file size (51991) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero

In [4]:
# for loop to format cell and join to one dataframe
list_of_df = []
for item in os.listdir(path10):
    full_path = os.path.join(path10, item)

    wb1 = exc.load_workbook(full_path)
    sh1 = wb1.active
    
    job = sh1.cell(row=6, column=4).value
    date = sh1.cell(row=11, column=4).value
    location = sh1.cell(row=10, column=4).value
    col1_name = sh1.cell(row=14, column=1).value
    sh1['B14'] = col1_name
    
    # sh1.move_range('B14:U200', rows=1, cols=1)
    rowlist = [13,12,11,10,9,8,7,6,5,4,3,2,1]
    collist = [19,17,14,13,10, 9, 8, 6, 5, 4, 3, 1]
    for x in rowlist:
        sh1.delete_rows(x)
    for y in collist:
        sh1.delete_cols(y)
    
    df = pd.DataFrame(sh1.values)
    df.columns = df.iloc[0]
    df = df[1:]
    df = df.dropna()
    
    df['job'] = job
    df['date'] = date
    df['location'] = location
    
    list_of_df.append(df)

full_df = pd.concat(list_of_df)

In [5]:
df_test = full_df
df_test = df_test[['Quantity', 'Rate', 'Days']].applymap(atof)

In [6]:
test2 = full_df
test2[['Quantity', 'Rate', 'Days']] = df_test[['Quantity', 'Rate', 'Days']]
test2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1740 entries, 1 to 92
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Crew Name    1740 non-null   object
 1   Description  1740 non-null   object
 2   Rate         1740 non-null   float64
 3   Method       1740 non-null   object
 4   Days         1740 non-null   float64
 5   Quantity     1740 non-null   float64
 6   UM           1740 non-null   object
 7   Unit Cost    1728 non-null   object
 8   Total Cost   1740 non-null   object
 9   job          1740 non-null   object
 10  date         93 non-null     object
 11  location     1638 non-null   object
dtypes: float64(3), object(9)
memory usage: 176.7+ KB

In [7]:
# only numeric-removes rows for alts and general conditions
reduced1 = test2[test2['Description'].str[0].str.isdigit()]
reduced1.shape

(1513, 12)

In [8]:
reduced_test = reduced1
reduced_test['Catagory'] = reduced_test['Description'].str[0:3]
reduced_test['Description'] = reduced_test['Description'].str[5:]

C:\Users\willd\AppData\Local\Temp\ipykernel_24376\185834724.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reduced_test['Catagory'] = reduced_test['Description'].str[0:3]
C:\Users\willd\AppData\Local\Temp\ipykernel_24376\185834724.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  reduced_test['Description'] = reduced_test['Description'].str[5:]

In [14]:
reduced_test

,Crew Name,Description,Rate,Method,Days,Quantity,UM,Unit Cost,Total Cost,job,date,location,Catagory
2,Asphalt Removal Crew,Site Clearing/Demolition,0.5,LOAD/PH,0.20,1.0,LOAD,$902.50,$902.50,Camp Pickle EWUT RFP #002,None,"Centennial, CO",1.2
3,Building Pad Fine Grade Crew,Grading To +/- One Tenth,1800.0,SF/PH,1.59,28673.0,SF,$0.27,"$7,645.76",Camp Pickle EWUT RFP #002,None,"Centennial, CO",1.6
5,Building Pad Fine Grade Crew,Grading To +/- One Tenth,500.0,SF/PH,2.82,14098.0,SF,$0.71,"$10,021.36",Camp Pickle EWUT RFP #002,None,"Centennial, CO",1.6
7,Cathodic Protection Crew,Water,0.0,LF/PH,0.00,96.0,LF,$0.00,$0.00,Camp Pickle EWUT RFP #002,None,"Centennial, CO",2.5
8,Cathodic Protection Crew,Water,0.0,LF/PH,0.00,144.0,LF,$0.00,$0.00,Camp Pickle EWUT RFP #002,None,"Centennial, CO",2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,Utility Labor Only - Grouting,Sanitary Sewer,2.0,PH/EACH,0.89,4.0,EACH,$580.58,"$2,322.32",Gunsmoke Saddle Ridge Apartments EWUT RFP #001,None,"Cheyenne, WY",2.2
89,Utility Labor Only - Grouting,Sanitary Sewer,1.0,PH/EACH,0.11,1.0,EACH,$290.29,$290.29,Gunsmoke Saddle Ridge Apartments EWUT RFP #001,None,"Cheyenne, WY",2.2
90,Utility Labor Only - Grouting,Storm Sewer & Drainage,1.0,PH/EACH,0.11,1.0,EACH,$290.29,$290.29,Gunsmoke Saddle Ridge Apartments EWUT RFP #001,None,"Cheyenne, WY",2.3
91,Water Line Testing Crew,Water,700.0,LF/DY,1.89,1320.0,LF,$2.90,"$3,822.49",Gunsmoke Saddle Ridge Apartments EWUT RFP #001,None,"Cheyenne, WY",2.4
92,Water Line Testing Crew,Water,1.0,EACH/DY,6.00,6.0,EACH,"$2,027.08","$12,162.47",Gunsmoke Saddle Ridge Apartments EWUT RFP #001,None,"Cheyenne, WY",2.4

In [12]:
df_wide = pd.pivot(reduced_test, index=['Crew Name'], columns = 'Method',values = reduced_test.Rate.mean())
df_wide

KeyError: 78.02689358889621

In [18]:
reduced_ew = reduced_test[reduced_test['Catagory'].str[0] == '2']
reduced_ew.shape

(1099, 13)

In [19]:
grouped = reduced_ew.groupby(['Crew Name', 'Method']).mean()
grouped

0                                            Rate      Days     Quantity
Crew Name                     Method
102" Box Base                 PH/EACH   18.000000  1.800000     1.000000
9Utility 330 Crew             LF/PH      9.000000  0.220000    18.000000
Backfill                      LF/PH     24.000000  2.640000   570.000000
                              PH/EACH    4.000000  0.420000     1.000000
Backfill Curb & Gutter        LF/PH     13.281667  0.676667    87.833333
...                                           ...       ...          ...
Utility 345 Structures        PH/EACH    7.416667  2.703333     3.833333
Utility Labor Only - Grouting PH/EACH    1.098039  0.443333     3.647059
Water Line Testing Crew       EACH/DY    1.000000  2.538462     2.538462
                              LF/DY    469.650000  1.877000  1063.000000
                              PH/EACH    5.000000  1.488000     3.000000

[93 rows x 3 columns]

In [ ]:
	Crew Name	Description	Rate	Method	Days	Quantity	UM	Unit Cost	Total Cost	job	date	locatio

In [42]:
# job = sh1.cell(row=6, column=4).value
# date = sh1.cell(row=11, column=4).value
# location = sh1.cell(row=10, column=4).value
# col1_name = sh1.cell(row=14, column=1).value
# sh1['B14'] = col1_name

'Ridgeline Vista (EWUT) RFP#002'

In [44]:
# # sh1.move_range('B14:U200', rows=1, cols=1)
# rowlist = [13,12,11,10,9,8,7,6,5,4,3,2,1]
# collist = [19,17,14,13,10, 9, 8, 6, 5, 4, 3, 1]
# for x in rowlist:
#     sh1.delete_rows(x)
# for y in collist:
#     sh1.delete_cols(y)

In [51]:
# df = pd.DataFrame(sh1.values)
# df.columns = df.iloc[0]
# df = df[1:]
# df = df.dropna()

In [52]:
# df['job'] = job
# df['date'] = date
# df['location'] = location